### ISSUE TITLE
HA MQTT availability is fragile

### ISSUE THREAD

**Issue by giorgi1324** [mrlt8/docker-wyze-bridge#907]
Hi, thanks for this amazing project!

I found that MQTT availability announcement logic in wyze-bridge doesn't play well with home assistant.

If I followed the code correctly, wyze-bridge announces itself as available on `wyzebridge/state` only when it starts. If home assistant misses this announcement because of the startup sequence of the services, then the camera entities stay unavailable in homeassistant until I manually `docker-compose restart wyze-bridge`. I found that the same happens if I restart mqtt broker but keep HA and wyze-bridge alive.

I think there are a couple of options around this issue:
1. Periodically announce "online" on  `wyzebridge/state` instead of doing this once on start.
2. Listen for HA "birth message" which by default it announces on `homeassistant/status` topic.

I think the first option is better because it's agnostic of the who's listening on the other side but I'm not the owner of this project so the call is not mine.

Cheers!

**Comment by mrlt8** [comment]
This should be fixed in [v2.3.10](https://github.com/mrlt8/docker-wyze-bridge/releases/tag/v2.3.10), and will attempt to update the status every 15 seconds and when the `homeassistant/status` changes to online.

**Comment by giorgi1324** [comment]
You the man!

**Comment by jhansche** [comment]
Just wanted to point out that this does not appear to resolve the problem of entities remaining unavailable after any of: a) MQTT broker restart, b) MQTT integration reload, or c) HA restart. The `wyzebridge/state=online` message does not actually fix the unavailable entities. It may work if the integration remembers the availability topic for that entity, but after the integration is reloaded, it does not remember that, and re-sending the /state topic does not fix the unavailable entities.

I've confirmed by listening to both the `homeassistant/status` topic and the `wyzebridge/state` topic, that when I reload the MQTT integration, I get:
* `homeassistant/status=offline`
* `homeassistant/status=online`
* `wyzebridge/state=online`

Yet even after `wyzebridge/state=online`, the unavailable entities remain unavailable, despite `wyzebridge/state` being the default for most discovered entities' `availability_topic`.

I opened #920 before I saw this issue, but I believe the suggestions in #920 are what we actually need to do to fix this (re-publish discovery after HA status becomes "online").
